---
title: "Generate Design Files"
author: "Sergio Mosquim Junior"
format:
  html:
    toc: true
    code-fold: true
    embed-resources: true
    toc-location: left
    smooth-scroll: true
engine: knitr
params:
  ref_design: '~/multiomics/data/merged_ids.tsv'
  proteome_design: '~/multiomics/data/proteomics/full/design_experiment_order.txt'
  phospho_design: '~/multiomics/data/proteomics/phospho/design_phospho_experiment_order.tsv'
  phospho_data: '~/multiomics/data/proteomics/phospho/230815_report.pr_matrix.tsv'
  proteome_out: '~/multiomics/results/design_files/mergedDesign_final.tsv'
  proteome_out_filtered: '~/multiomics/results/design_files/mergedDesign_final_filtered.tsv'
  phospho_out: '~/multiomics/results/design_files/mergedDesign_PHOSPHO_final.tsv'
  phospho_out_filtered: '~/multiomics/results/design_files/mergedDesign_PHOSPHO_Filtered.tsv'
  proteome_noPool: '~/multiomics/results/design_files/design_Full_noPool.tsv'
  phospho_noPool: '~/multiomics/results/design_files/design_phospho_noPool.tsv'
  transcriptome_noPool: '~/multiomics/results/design_files/design_RNA_noPool.tsv'
  proteome_ductal: '~/multiomics/results/design_files/design_full_ductal.tsv'
  phospho_ductal: '~/multiomics/results/design_files/design_phospho_ductal.tsv'
  transcriptome_ductal: '~/multiomics/results/design_files/design_RNA_ductal.tsv'
  proteome_lobular: '~/multiomics/results/design_files/design_full_lobular.tsv'
  phospho_lobular: '~/multiomics/results/design_files/design_phospho_lobular.tsv'
  transcriptome_lobular: '~/multiomics/results/design_files/design_RNA_lobular.tsv'
---

# Requires Packages:
```{r}
#| message: false
#| warning: false
library(tidyverse)
```

# Base Design Files
## Full Proteome
```{r Design Files Full Proteome Data}
#| message: false
referenceDesign <- read_tsv(file = params$ref_design,col_names = TRUE)
batchDesign <- read_tsv(file = params$proteome_design) %>% 
  mutate(across(.cols = where(is.character),.fns = ~str_replace_all(string = .x,pattern = '\\-',replacement = '\\_')))

mergedDesign <- left_join(x = batchDesign,y = referenceDesign, by= join_by(sample_id==Sample), keep=TRUE)
write_tsv(x = mergedDesign,file = params$proteome_out)

samplesToRemove <- c('S000785','S003045','S002208','S000621','S000454')
designFiltered <- mergedDesign %>% 
  filter(!(sample_id %in% samplesToRemove))
write_tsv(x = designFiltered,file = params$proteome_out_filtered)
```

## Phosphoproteome
```{r Design Files Phospho Data}
#| message: false

# In the pdf report from DIA-NN, there are samples which have less than 10 000 precursors at 1% FDR. Therefore, before proceeding, these samples will be removed. A design file will be created to allow for that
referenceDesign <- read_tsv(file = params$ref_design, col_names = TRUE)
designPhospho <- read_tsv(file = params$phospho_design) %>% 
  mutate(across(.cols = where(is.character),.fns = ~str_replace_all(string = .x,pattern = '\\-',replacement = '\\_')))
mergedDesign <- left_join(x = designPhospho,y = referenceDesign, by= join_by(sample_id==Sample), keep=TRUE)

data <- read_tsv(file = params$phospho_data) %>% 
  mutate(across(where(is.double),~na_if(.,0.0))) %>% 
  mutate(across(where(is.double),~na_if(.,0)))

newColNames <- data %>%
  select(-c(1:10)) %>%
  colnames()
newColNames <- newColNames %>%
  str_extract(pattern = '(?<=\\\\)[:digit:]{6}\\_[:graph:]+(?=\\.mzML\\.dia)') %>%
  str_replace_all(pattern = '\\-',replacement = '\\_')
newColNames <- c(colnames(data)[1:10],newColNames)
colnames(data) <- newColNames

newData <- data %>% 
  select(mergedDesign$file_name)
colnames(newData) <- mergedDesign$sample_id

newDesign <- newData %>% 
  map(.x = ., .f = ~sum(!is.na(.x))) %>%
  simplify(.) %>% 
  tibble(sample_id = names(.),Precursors = .) %>% 
  left_join(x=mergedDesign,y=.,by="sample_id")
designFiltered <- newDesign %>% 
  filter(Precursors >= 10000)

write_tsv(x = newDesign,file = params$phospho_out)
write_tsv(x = designFiltered, file = params$phospho_out_filtered)
```





# Design Files without Pool samples
## Proteome
```{r}
newDesign <- read_tsv(file = params$proteome_out_filtered) %>% 
  filter(str_detect(string = sample_id, pattern = 'Pool', negate = TRUE))

write_tsv(x = newDesign,file = params$proteome_noPool)
```

## Phosphoproteome
```{r}
newDesign <- read_tsv(file = params$phospho_out_filtered) %>% 
  filter(str_detect(string = sample_id, pattern = 'POOL', negate = TRUE))

write_tsv(x = newDesign,file = params$phospho_noPool)
```

## Transcriptome
```{r}
newDesign <- read_tsv(file = params$proteome_out) %>% 
  filter(str_detect(string = sample_id, pattern = 'Pool', negate = TRUE))

write_tsv(x = newDesign,file = params$transcriptome_noPool)
```

# Design Files only Ductal (no Pool)
## Proteome
```{r}
newDesign <- read_tsv(file = params$proteome_noPool) %>% 
  filter(str_detect(string = InvCa.type, pattern = 'Ductal'))

write_tsv(x = newDesign,file = params$proteome_ductal)
```

## Phosphoproteome
```{r}
newDesign <- read_tsv(file = params$phospho_noPool) %>% 
  filter(str_detect(string = InvCa.type, pattern = 'Ductal'))

write_tsv(x = newDesign,file = params$phospho_ductal)
```

## Transcriptome
```{r}
newDesign <- read_tsv(file = params$transcriptome_noPool) %>% 
  filter(str_detect(string = InvCa.type, pattern = 'Ductal'))

write_tsv(x = newDesign,file = params$transcriptome_ductal)
```

# Design Files only Lobular (no Pool)
## Proteome
```{r}
newDesign <- read_tsv(file = params$proteome_noPool) %>% 
  filter(str_detect(string = InvCa.type, pattern = 'Lobular'))

write_tsv(x = newDesign,file = params$proteome_lobular)
```

## Phosphoproteome
```{r}
newDesign <- read_tsv(file = params$phospho_noPool) %>% 
  filter(str_detect(string = InvCa.type, pattern = 'Lobular'))

write_tsv(x = newDesign,file = params$phospho_lobular)
```

## Transcriptome
```{r}
newDesign <- read_tsv(file = params$transcriptome_noPool) %>% 
  filter(str_detect(string = InvCa.type, pattern = 'Lobular'))

write_tsv(x = newDesign,file = params$transcriptome_lobular)
```