---
title: "Data pre-processing"
author: "Sergio Mosquim Junior"
format:
  html:
    toc: true
    code-fold: true
    embed-resources: true
    toc-location: left
    smooth-scroll: true
engine: knitr
---

# Requires Packages:
```{r required packages}
#| message: false
#| warning: false
library(tidyverse)
library(NormalyzerDE)
library(data.table)
library(future)
library(future.callr)
library(furrr)
```
```{r}
set.seed(123)
workers <- as.integer(Sys.getenv("NXF_TASK_CPUS", "1"))
plan(callr,workers=workers)
on.exit(expr = {plan(sequential)})
```


# Data Pre-processing

## Transcriptomics Data
```{r Transcriptomics Data preprocessing}
#| message: false
# Data Downloaded from https://data.mendeley.com/datasets/yzxtxn4nmd
load('/home/multiomics/data/transcriptomics/Gene.ID.ann.Rdata')
load('/home/multiomics/data/transcriptomics/SCANB.9206.genematrix_noNeg.Rdata')
design <- read_tsv('/home/multiomics/results/design_files/mergedDesign_ref_hisscore.tsv') %>% 
  filter(!is.na(GEX.assay))

geneNames <- rownames(SCANB.9206.genematrix_noNeg) %>% 
  data.frame(Gene.ID=.) %>% 
  left_join(.,Gene.ID.ann)

newGenes <- SCANB.9206.genematrix_noNeg %>% 
  as_tibble() %>% 
  dplyr::select(design$GEX.assay)

sampleNames <- newGenes %>% 
  colnames %>% 
  str_split_i(pattern = '\\.',i = 1)

colnames(newGenes) <- sampleNames
newGenes <- newGenes %>% 
  performCyclicLoessNormalization(noLogTransform = FALSE)

# Running this step as data.table for memory efficiency
# newGenes <- as.data.table(newGenes)
# newGenes <- newGenes[, lapply(.SD, function(x) x - mean(x,na.rm=TRUE)), by = .I]

# The row order between the annotation matrix and the gene matrix is the same, so one can just swap gene names
newGenes <- bind_cols(geneNames,newGenes)
outputdir <- "/home/multiomics/results/normalization/transcriptomics/"
if(!dir.exists(paths = outputdir)) {
  dir.create(path = outputdir,recursive = TRUE)
}
write_tsv(x = newGenes,file =  paste0(outputdir,'genematrix_adjusted_cycloess.tsv'))
rm(list = ls())
invisible(gc())
```

## Proteomics Data
### DIA-NN Peptide
#### Data Clean-up
```{r peptide data cleanup}
#| message: false
mergedDesign <- read_tsv(file = '/home/multiomics/results/design_files/mergedDesign_final.tsv')
data <- read_tsv(file = '/home/multiomics/data/proteomics/full/230814_report.pr_matrix.tsv') %>% 
  mutate(across(where(is.double),~na_if(.,0.0))) %>% 
  mutate(across(where(is.double),~na_if(.,0))) %>% 
  dplyr::filter(str_detect(Protein.Group,'^Cont\\_{1}[:alnum:]{6}(?!\\;)',negate = TRUE)) #remove rows with contaminant as single ID

newColNames <- data %>%
  select(-c(1:10)) %>%
  colnames()
newColNames <- newColNames %>%
  str_extract(pattern = '(?<=\\\\)[:digit:]{6}\\_[:graph:]+(?=\\.mzML\\.dia)') %>%
  str_replace_all(pattern = '\\-',replacement = '\\_')
newColNames <- c(colnames(data)[1:10],newColNames)
colnames(data) <- newColNames

newData <- data %>% 
  select(mergedDesign$file_name)
colnames(newData) <- mergedDesign$sample_id
newData <- bind_cols(data[,1:10],newData)

outputdir <- "/home/multiomics/results/normalization/fullproteome/"
if(!dir.exists(paths = outputdir)) {
  dir.create(path = outputdir,recursive = TRUE)
}
write_tsv(x = newData,file = paste0(outputdir, "report.pr_matrix_clean.tsv"))
```

#### Peptide-level Normalization
```{r peptide level normalization}
jobName <- 'peptide_normalization'
dataP <- paste0(outputdir, "report.pr_matrix_clean.tsv")
designP <- '/home/multiomics/results/design_files/mergedDesign_final.tsv'
outputP <- '/home/multiomics/results/normalization/fullproteome'

proteomePepNorm <- future(seed = TRUE,globals = c("jobName", "dataP", "designP", "outputP"), lazy = TRUE,gc = TRUE,expr = {normalyzer(jobName = jobName,designPath = designP,dataPath = dataP,outputDir = outputP,normalizeRetentionTime = FALSE,zeroToNA = TRUE,sampleColName = 'sample_id',groupColName = 'ms_run_order',writeReportAsPngs = TRUE, skipAnalysis = TRUE)})

varsKeep <- c('proteomePepNorm','proteomeProtNorm','phosphoPepNorm','results', 'varsKeep')
rm(list = c(setdiff(x = ls(),y = varsKeep)))
invisible(gc())
```

### DIA-NN Protein Group Table
#### Data Clean-up
```{r protein data cleanup}
data <- read_tsv(file = '/home/multiomics/data/proteomics/full/230814_report.pg_matrix.tsv') %>% 
  mutate(across(where(is.double),~na_if(.,0.0))) %>% 
  mutate(across(where(is.double),~na_if(.,0))) %>% 
  filter(str_detect(Protein.Group,'^Cont\\_{1}[:alnum:]{6}(?!\\;)',negate = TRUE))
designP <- '/home/multiomics/results/design_files/mergedDesign_final.tsv'
design <- read_tsv(designP)

newColNames <- data %>% 
  select(-c(1:5)) %>% 
  colnames()
newColNames <- newColNames %>%
  str_extract(pattern = '(?<=\\\\)[:digit:]{6}\\_[:graph:]+(?=\\.mzML\\.dia)') %>% 
  str_replace_all(pattern = '\\-',replacement = '\\_')
newColNames <- c(colnames(data)[1:5],newColNames)
colnames(data) <- newColNames

newData <- data %>% 
  select(design$file_name)
colnames(newData) <- design$sample_id
newData <- bind_cols(data[,1:5],newData)

outputdir <- "/home/multiomics/results/normalization/fullproteome/"
if(!dir.exists(paths = outputdir)) {
  dir.create(path = outputdir,recursive = TRUE)
}
write_tsv(x = newData,file = paste0(outputdir, "report.pg_matrix_clean.tsv"))
```

#### Protein-level Normalization
```{r protein level normalization}
jobName <- 'protein_normalization'
dataP <- paste0(outputdir, "report.pg_matrix_clean.tsv")
designP <- '/home/multiomics/results/design_files/mergedDesign_final.tsv'
outputP <- '/home/multiomics/results/normalization/fullproteome'

proteomeProtNorm <- future(seed = TRUE,globals = c("jobName", "dataP", "designP", "outputP"),gc = TRUE,expr = {normalyzer(jobName = jobName,designPath = designP,dataPath = dataP,outputDir = outputP,normalizeRetentionTime = FALSE,zeroToNA = TRUE,sampleColName = 'sample_id',groupColName = 'ms_run_order',writeReportAsPngs = TRUE, skipAnalysis = TRUE)})

varsKeep <- c('proteomePepNorm','proteomeProtNorm','phosphoPepNorm','results', 'varsKeep')
rm(list = c(setdiff(x = ls(),y = varsKeep)))
invisible(gc())
```


## Phosphoproteomics Data
### DIA-NN Peptide
#### Data Clean-up
```{r}
dataP <- '/home/multiomics/data/proteomics/phospho/230815_report.pr_matrix.tsv'

# In the pdf report from DIA-NN, there are samples which have less than 10 000 precursors at 1% FDR. Therefore, before proceeding, these samples will be removed.
mergedDesign <- read_tsv(file = '/home/multiomics/results/design_files/mergedDesign_PHOSPHO_Filtered.tsv')
data <- read_tsv(dataP) %>% 
  mutate(across(where(is.double),~na_if(.,0.0))) %>% 
  mutate(across(where(is.double),~na_if(.,0))) %>% 
  filter(str_detect(Protein.Group,'^Cont\\_{1}[:alnum:]{6}(?!\\;)',negate = TRUE))

newColNames <- data %>%
  dplyr::select(-c(1:10)) %>%
  colnames()
newColNames <- newColNames %>%
  str_extract(pattern = '(?<=\\\\)[:digit:]{6}\\_[:graph:]+(?=\\.mzML\\.dia)') %>%
  str_replace_all(pattern = '\\-',replacement = '\\_')
newColNames <- c(colnames(data)[1:10],newColNames)
colnames(data) <- newColNames

newData <- data %>% 
  dplyr::select(mergedDesign$file_name)
colnames(newData) <- mergedDesign$sample_id
newData <- bind_cols(data[,1:10],newData) %>% 
  filter(str_detect(Modified.Sequence,'UniMod\\:21'))

outputdir <- "/home/multiomics/results/normalization/phosphoproteome/"
if(!dir.exists(paths = outputdir)) {
  dir.create(path = outputdir,recursive = TRUE)
}
write_tsv(x = newData,file = paste0(outputdir, "report.pr_matrix_clean.tsv"))
```

#### Peptide-level Normalization
```{r}
jobName <- 'peptide_normalization'
dataP <- paste0(outputdir, "report.pr_matrix_clean.tsv")
designP <- '/home/multiomics/results/design_files/mergedDesign_PHOSPHO_Filtered.tsv'
outputP <- '/home/multiomics/results/normalization/phosphoproteome'

phosphoPepNorm <- future(seed = TRUE,globals = c("jobName", "dataP", "designP", "outputP"),gc = TRUE,expr = {normalyzer(jobName = jobName,designPath = designP,dataPath = dataP,outputDir = outputP,normalizeRetentionTime = FALSE,zeroToNA = TRUE,sampleColName = 'sample_id',groupColName = 'ms_run_order', skipAnalysis = TRUE)})
```

## Results Normalization
```{r}
results <- list(proteomePepNorm,proteomeProtNorm,phosphoPepNorm)
varsKeep <- c('proteomePepNorm','proteomeProtNorm','phosphoPepNorm','results')
rm(list = c(setdiff(x = ls(),y = varsKeep)))
invisible(gc())

future_map(.x = results,.f = value)
```

